// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[slug].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/create.ts";
import * as $3 from "./routes/api/shortener/[slug].ts";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/ShortenerForm.tsx";

const manifest = {
	routes: {
		"./routes/[slug].tsx": $0,
		"./routes/_app.tsx": $1,
		"./routes/api/create.ts": $2,
		"./routes/api/shortener/[slug].ts": $3,
		"./routes/index.tsx": $4,
	},
	islands: {
		"./islands/Counter.tsx": $$0,
		"./islands/ShortenerForm.tsx": $$1,
	},
	baseUrl: import.meta.url,
	config,
};

export default manifest;
